staging:
  domain: yafeilee.me
  deploy_to: /home/ruby/cywin_staging
  repository: git@github.com:windy/cywin.git
  branch: staging
demo:
  domain: yafeilee.me
  deploy_to: /home/ruby/cywin_demo
  repository: git@github.com:windy/cywin.git
  branch: master
